<a href="https://colab.research.google.com/github/letrongminh/Torch4GANs/blob/main/Torch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [152]:
import torch

In [153]:
# Tensor
t1 = torch.tensor(4.)
t1

tensor(4.)

In [154]:
# Matrix
t2 = torch.tensor([[5., 6.], [7., 8.]])
t2

tensor([[5., 6.],
        [7., 8.]])

In [155]:
t2.shape

torch.Size([2, 2])

#**Tensor operations and gradients**

In [156]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
y = w*x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [157]:
# Đạo hàm - Derivatives
y.backward()

In [158]:
# Display Gradient
print('dy/dx', x.grad)
print('dy/dw', w.grad)

dy/dx None
dy/dw tensor(3.)


#Torch with numpy

In [159]:
# convert a Numpy array to a Torch tensor
import numpy as np

x = np.array([[1,2], [3, 4.]])
print(x)
print("==============")
y = torch.from_numpy(x)
y

[[1. 2.]
 [3. 4.]]


tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

# LR from scratch w Torch

In [171]:
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype = 'float32')
target = np.array([[56, 70],
                   [81, 101],
                   [119, 133],
                   [22, 37],
                   [103, 119]], dtype = 'float32')

In [172]:
#convert from numpy to Torch Tensor
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(target)

In [173]:
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)

In [174]:
def model(x):
  return x @ w.t() + b

@ represent matrix multiplication in PyTorch

**.t()** methos returns the transpose of a Tensor


In [182]:
# Generate predict
predict = model(inputs)
predict

tensor([[ -24.3831, -117.9704],
        [ -23.8321, -143.1403],
        [   0.3653, -128.4791],
        [ -68.5857, -181.9796],
        [   5.2960,  -96.0345]], grad_fn=<AddBackward0>)

In [183]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [184]:
#Compute Loss
def mse(t1, t2):
  diff = t1-t2
  return torch.sum(diff*diff)/diff.numel()

loss = mse(predict, targets)
print(loss)

tensor(30677.7852, grad_fn=<DivBackward0>)


In [187]:
print(w)
print(b)
print(w.grad.zero_())

tensor([[-0.8643,  0.6662,  0.5280],
        [-1.6032,  0.5840,  0.5651]], requires_grad=True)
tensor([-0.0227,  0.8839], requires_grad=True)
tensor([[0., 0., 0.],
        [0., 0., 0.]])


**Train multiple epochs**

In [188]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(predict, targets)
    
    #Compute Gradient
    loss.backward()

    # Adjust weights & reset gradients to 0
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.zero_grad()
        b.zero_grad()

RuntimeError: ignored

# **Linear regression using PyTorch built-ins**

In [189]:
import torch.nn as nn

In [190]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')
#convert from numpy array to Torch Tensor
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

# Data Loader

In [220]:
from torch.utils.data import TensorDataset, DataLoader

In [221]:
# The TensorDataset cho phép truy cập vào phận nhỏ data khi chúng ta sử dụng 
# array indexing ([0:3] in the bottombottom code)
train_ = TensorDataset(inputs, targets)
train_[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [223]:
# Sử dụng DataLoader để chia data thành các phần nhỏ (using Batch Size)
train_batch = DataLoader(train_, batch_size=5, shuffle=True)

In [224]:
# Implement data splited =))
for x, y in train_batch:
  print(x)
  print(y)

tensor([[91., 87., 65.],
        [68., 97., 70.],
        [73., 66., 44.],
        [68., 96., 71.],
        [73., 67., 43.]])
tensor([[ 80., 102.],
        [102., 120.],
        [ 57.,  69.],
        [104., 118.],
        [ 56.,  70.]])
tensor([[ 92.,  87.,  64.],
        [ 88., 134.,  59.],
        [ 69.,  96.,  70.],
        [101.,  44.,  37.],
        [ 87., 134.,  58.]])
tensor([[ 82., 100.],
        [118., 132.],
        [103., 119.],
        [ 21.,  38.],
        [119., 133.]])
tensor([[102.,  43.,  37.],
        [ 91.,  88.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 74.,  66.,  43.]])
tensor([[ 22.,  37.],
        [ 81., 101.],
        [118., 134.],
        [ 20.,  38.],
        [ 57.,  69.]])


# nn.Linear

In [247]:
# khởi tạo model, model sẽ tự sinh ra một ma trận trọng số và một ma trận bias
# Sau đó sẽ đi tối ưu với thuật toán tối ưu
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.3087,  0.4504, -0.2256],
        [ 0.1607,  0.3971, -0.1317]], requires_grad=True)
Parameter containing:
tensor([ 0.3009, -0.4918], requires_grad=True)


In [248]:
# **parameters** trong Torch là hữu ích
# nó trả về ma trận Weight và ma trận Bias
list(model.parameters())

[Parameter containing:
 tensor([[-0.3087,  0.4504, -0.2256],
         [ 0.1607,  0.3971, -0.1317]], requires_grad=True),
 Parameter containing:
 tensor([ 0.3009, -0.4918], requires_grad=True)]

In [249]:
# Predictions
predict = model(inputs)
predict

tensor([[ -1.7594,  32.1762],
        [ -2.5958,  40.6403],
        [ 20.7102,  59.0531],
        [-20.1666,  28.0963],
        [  6.4446,  39.4918],
        [ -2.5184,  31.9398],
        [ -3.2718,  40.1115],
        [ 20.1759,  59.0821],
        [-19.4076,  28.3327],
        [  6.5276,  39.1994],
        [ -2.4354,  31.6474],
        [ -3.3549,  40.4039],
        [ 21.3862,  59.5819],
        [-20.2497,  28.3887],
        [  7.2036,  39.7282]], grad_fn=<AddmmBackward>)

# Loss Function

In [250]:
# Sử dụng MSE Loss
loss_func = torch.nn.functional.mse_loss

# Optimization

In [251]:
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

# Train the model

In [252]:
def fit(num_epochs, model, loss_function, optimize, train_batch):
  for epoch in range(num_epochs):
    for x_train, y_train in train_batch:
      
      # Generate predictions
      predictions = model(x_train)

      # Calculate Loss
      loss = loss_function(predictions, y_train)

      # Compute Gradient
      loss.backward()

      # Update parameters using gradient ( throught optimiser)
      optimize.step()

      # Reset the gradient to 0
      optimize.zero_grad()
    
    # Print the progress
    if (epoch+1) % 10 == 0:
      print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [254]:
fit(1000, model, loss_func, opt, train_batch)

Epoch [10/1000], Loss: 11.9115
Epoch [20/1000], Loss: 28.2825
Epoch [30/1000], Loss: 18.6537
Epoch [40/1000], Loss: 9.6360
Epoch [50/1000], Loss: 22.4713
Epoch [60/1000], Loss: 18.2590
Epoch [70/1000], Loss: 3.9484
Epoch [80/1000], Loss: 2.2124
Epoch [90/1000], Loss: 16.7893
Epoch [100/1000], Loss: 10.3320
Epoch [110/1000], Loss: 9.8391
Epoch [120/1000], Loss: 9.8578
Epoch [130/1000], Loss: 9.7273
Epoch [140/1000], Loss: 13.0325
Epoch [150/1000], Loss: 5.4175
Epoch [160/1000], Loss: 12.3746
Epoch [170/1000], Loss: 10.2088
Epoch [180/1000], Loss: 4.8064
Epoch [190/1000], Loss: 7.4762
Epoch [200/1000], Loss: 6.0291
Epoch [210/1000], Loss: 5.9383
Epoch [220/1000], Loss: 8.1939
Epoch [230/1000], Loss: 7.4324
Epoch [240/1000], Loss: 8.9335
Epoch [250/1000], Loss: 7.7860
Epoch [260/1000], Loss: 6.6561
Epoch [270/1000], Loss: 6.5931
Epoch [280/1000], Loss: 5.5917
Epoch [290/1000], Loss: 5.9711
Epoch [300/1000], Loss: 3.6283
Epoch [310/1000], Loss: 2.3924
Epoch [320/1000], Loss: 3.9094
Epoch [